name: Config Tests
on: [push, pull_request]
jobs:
  Run-Config-Tests:
    runs-on: windows-latest
    steps:
      - name: STEP 1 - Setup build environment
        run: .\scripts\build_env.ps1
      - name: STEP 2 - Install pytest
        run: python -m pip install --upgrade pytest pytest-helpers-namespace
      - name: STEP 3 - Check out repository code
        uses: actions/checkout@v2
      - name: STEP 4 - Check out salt repository
        run: git clone https://github.com/saltstack/salt.git ..\salt
      - name: STEP 5 - Build test binary
        run: .\tests\build_test_pkg.bat
      - name: STEP 6 - Run config tests
        run: pytest -vvv -- .\tests\config_tests\
